#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "Zebrafishes"
SAMPLES: "samples.tsv"
ANNOFILE: "annotations.txt"
Control: "Control"
KO: "KO"
